//! Optional Codex app-server transport. Authentication stays inside Codex.
use serde_json::{Value, json};
use std::{
    io::{BufRead, BufReader, Write},
    path::{Path, PathBuf},
    process::{Child, Command, Stdio},
    sync::mpsc,
};

/// v2 GetAccountResponse / Account, generated by `codex app-server generate-ts`.
/// Presence of an account indicates authentication; requiresOpenaiAuth does not.
pub(crate) fn account_label(result: &Value) -> Result<Option<String>, String> {
    let account = result
        .get("account")
        .ok_or("Missing Codex account response")?;
    if account.is_null() {
        return Ok(None);
    }
    if !account.is_object() {
        return Err("Invalid Codex account response".into());
    }
    let label = match account["type"].as_str() {
        Some("apiKey") => "API key".into(),
        Some("chatgpt") => {
            let mut parts = vec!["ChatGPT"];
            for key in ["email", "planType"] {
                if let Some(value) = account[key].as_str().filter(|s| !s.is_empty()) {
                    parts.push(value);
                }
            }
            parts.join(" · ")
        }
        _ => "Signed in".into(),
    };
    Ok(Some(label))
}

#[derive(Clone, Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct Model {
    pub model: String,
    pub display_name: String,
    #[serde(default)]
    pub default_reasoning_effort: Option<String>,
    #[serde(default)]
    pub supported_reasoning_efforts: Vec<EffortOption>,
    #[serde(default)]
    pub hidden: bool,
}

#[derive(Clone, Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct EffortOption {
    pub reasoning_effort: String,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct ModelPage {
    pub data: Vec<Model>,
    pub next_cursor: Option<String>,
}

pub(crate) fn model_page(result: &Value) -> Result<ModelPage, String> {
    let mut page: ModelPage = serde_json::from_value(result.clone())
        .map_err(|e| format!("Invalid Codex model list: {e}"))?;
    page.data.retain(|m| !m.hidden && !m.model.is_empty());
    Ok(page)
}

pub(crate) fn selected_model<'a>(
    models: &'a [Model],
    preferred: Option<&str>,
) -> Option<&'a Model> {
    models
        .iter()
        .find(|m| Some(m.model.as_str()) == preferred)
        .or_else(|| models.first())
}

pub(crate) fn selected_effort<'a>(
    model: Option<&'a Model>,
    preferred: Option<&'a str>,
) -> Option<&'a str> {
    preferred
        .filter(|effort| {
            !effort.is_empty()
                && model.is_none_or(|m| {
                    m.supported_reasoning_efforts
                        .iter()
                        .any(|e| e.reasoning_effort == *effort)
                })
        })
        .or_else(|| model.and_then(|m| m.default_reasoning_effort.as_deref()))
}

/// Describe the same catalog fallback used for turn submission, retaining a
/// warning when a saved preference no longer names an available model.
pub(crate) fn resolved_model_label(
    models: &[Model],
    preferred: Option<&str>,
) -> (String, Option<String>) {
    let resolved = selected_model(models, preferred)
        .map(|m| m.display_name.as_str())
        .unwrap_or("Codex default");
    let warning = preferred
        .filter(|name| !models.iter().any(|m| m.model == *name))
        .map(|name| format!("Saved model {name} unavailable · using {resolved}"));
    let label = if preferred.is_none() {
        format!("Automatic · {resolved}")
    } else {
        resolved.to_owned()
    };
    (label, warning)
}

fn effort_label(value: &str) -> String {
    match value {
        "xhigh" => "Extra high".into(),
        _ => {
            let mut chars = value.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_uppercase().collect::<String>() + chars.as_str()
            })
        }
    }
}

/// Model-default first, followed by supported levels in increasing effort order
/// (unknown levels retain catalog order). None or an unsupported preference
/// selects only model-default; explicit preferences select only their own level.
/// Without a catalog model, retain a non-empty preference as the selected level
/// sent with the turn; otherwise select model-default and omit the effort.
pub(crate) fn effort_choices(
    model: Option<&Model>,
    preferred: Option<&str>,
) -> Vec<(Option<String>, String, bool)> {
    let mut levels: Vec<&str> = Vec::new();
    if let Some(model) = model {
        for option in &model.supported_reasoning_efforts {
            let value = option.reasoning_effort.as_str();
            if !value.is_empty() && !levels.contains(&value) {
                levels.push(value);
            }
        }
    } else if let Some(value) = preferred.filter(|value| !value.is_empty()) {
        levels.push(value);
    }
    levels.sort_by_key(|value| {
        ["low", "medium", "high", "xhigh"]
            .iter()
            .position(|known| known == value)
            .unwrap_or(4)
    });
    let preferred = preferred.filter(|value| levels.contains(value));
    let default_label = model
        .and_then(|m| m.default_reasoning_effort.as_deref())
        .filter(|value| !value.is_empty())
        .map(|value| format!("Model default ({})", effort_label(value)))
        .unwrap_or_else(|| "Model default".into());
    let mut choices = vec![(None, default_label, preferred.is_none())];
    choices.extend(levels.into_iter().map(|value| {
        (
            Some(value.to_owned()),
            effort_label(value),
            preferred == Some(value),
        )
    }));
    choices
}

pub(crate) fn turn_params(
    thread: &str,
    input: Vec<Value>,
    model: Option<&str>,
    effort: Option<&str>,
) -> Value {
    let mut params = json!({"threadId":thread,"input":input,"summary":"detailed"});
    if let Some(effort) = effort {
        params["effort"] = json!(effort);
    }
    if let Some(model) = model {
        params["model"] = json!(model);
    }
    params
}
pub(crate) struct Client {
    child: Child,
    tx: mpsc::Sender<Value>,
    rx: mpsc::Receiver<Result<Value, String>>,
    pub directory: PathBuf,
}
impl Drop for Client {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
        let _ = std::fs::remove_dir_all(&self.directory);
    }
}
impl Client {
    pub fn start() -> Result<Self, String> {
        let executable = executable().ok_or(
            "Codex CLI not found. Install Codex, or set REXAFS_CODEX to its executable path.",
        )?;
        let directory = std::env::temp_dir().join(format!(
            "rexafs-assistant-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis()
        ));
        let mut builder = std::fs::DirBuilder::new();
        #[cfg(unix)]
        {
            use std::os::unix::fs::DirBuilderExt;
            builder.mode(0o700);
        }
        builder.create(&directory).map_err(|e| e.to_string())?;
        let mut child = Command::new(executable)
            .args([
                "-c",
                "features.shell_tool=false",
                "-c",
                "features.unified_exec=false",
                "-c",
                "features.apps=false",
                "-c",
                "features.multi_agent=false",
                "-c",
                "web_search=\"disabled\"",
                "app-server",
            ])
            .current_dir(&directory)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::null())
            .spawn()
            .map_err(|e| format!("Could not start Codex: {e}"))?;
        let mut stdin = child.stdin.take().ok_or("Codex stdin unavailable")?;
        let stdout = child.stdout.take().ok_or("Codex stdout unavailable")?;
        let (tx, outgoing) = mpsc::channel::<Value>();
        let (incoming, rx) = mpsc::channel();
        let errors = incoming.clone();
        std::thread::spawn(move || {
            while let Ok(v) = outgoing.recv() {
                if let Err(e) = writeln!(stdin, "{v}").and_then(|_| stdin.flush()) {
                    let _ = errors.send(Err(format!("Codex connection closed: {e}")));
                    break;
                }
            }
        });
        std::thread::spawn(move || {
            for line in BufReader::new(stdout).lines() {
                match line {
                    Ok(line) => match serde_json::from_str(&line) {
                        Ok(v) => {
                            if incoming.send(Ok(v)).is_err() {
                                return;
                            }
                        }
                        Err(_) => {
                            let _ = incoming
                                .send(Err("Codex returned an invalid protocol message".into()));
                        }
                    },
                    Err(e) => {
                        let _ = incoming.send(Err(e.to_string()));
                        return;
                    }
                }
            }
            let _ = incoming.send(Err("Codex disconnected".into()));
        });
        Ok(Self {
            child,
            tx,
            rx,
            directory,
        })
    }
    pub fn send(&self, v: Value) -> Result<(), String> {
        self.tx.send(v).map_err(|_| "Codex disconnected".into())
    }
    pub fn drain(&self) -> Vec<Result<Value, String>> {
        self.rx.try_iter().take(200).collect()
    }
}
fn executable() -> Option<PathBuf> {
    if let Some(path) = crate::settings::env_var_os("CODEX") {
        return Path::new(&path).is_file().then(|| path.into());
    }
    let mut paths: Vec<_> = std::env::var_os("PATH")
        .map(|p| std::env::split_paths(&p).map(|p| p.join("codex")).collect())
        .unwrap_or_default();
    if let Some(home) = crate::settings::home_dir() {
        paths.extend([
            home.join(".bun/bin/codex"),
            home.join(".local/bin/codex"),
            home.join(".npm-global/bin/codex"),
        ]);
    }
    paths.extend([
        PathBuf::from("/opt/homebrew/bin/codex"),
        PathBuf::from("/usr/local/bin/codex"),
    ]);
    paths.into_iter().find(|p| p.is_file())
}
pub(crate) fn initialize(id: u64) -> Value {
    json!({"id":id,"method":"initialize","params":{"clientInfo":{"name":"rexafs","title":"rexafs","version":env!("CARGO_PKG_VERSION")},"capabilities":{"experimentalApi":true}}})
}
pub(crate) fn dynamic_tools() -> Value {
    json!([
    {"type":"function","name":"xray_set_layout","description":"Change visible panels and the main desktop window. File browser/inspector and current/marked plot scope are presentation only. Window actions: focus_app, maximize_app (resize to display), restore_app, resize_app. Read-only analysis mode allows presentation changes.","inputSchema":{"type":"object","properties":{"file_browser":{"type":"boolean"},"inspector":{"type":"boolean"},"plot_scope":{"type":"string","enum":["current","marked"]},"window_action":{"type":"string","enum":["focus_app","maximize_app","restore_app","resize_app"]},"width":{"type":"number"},"height":{"type":"number"}},"additionalProperties":false}},
    {"type":"function","name":"xray_get_plots","description":"Inspect the current processing stage or fit results: returns fresh plots plus resolved numerical settings. Navigate to Normalize, Background and Transform and inspect each before running a fit. Respects the Plots switch.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}},
    {"type":"function","name":"xray_search_structures","description":"Search the curated reference-structure library and display Structure. Returns candidates with stable ids; do not infer metallic composition merely from an element name.","inputSchema":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"],"additionalProperties":false}},
    {"type":"function","name":"xray_choose_structure","description":"Choose a returned curated structure id; display its crystal and 8 Å cluster preview. Returns absorber, edge and site information for inspection.","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"],"additionalProperties":false}},
    {"type":"function","name":"xray_calculate_paths","description":"Run the selected FEFF/ReFEFF backend using the inspected structure, absorber and cluster. Shows Calculate, waits for completion, then shows Paths. Reuse suitable calculated paths; do not duplicate calculations without reason.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}},
    {"type":"function","name":"xray_select_paths","description":"Assign an explicit list of already calculated FEFF files. For multiple-spectrum fits dataset_id is required. Preserves existing expressions; rebuild_parameters=true explicitly regenerates the parameter template and should only be used for a new model.","inputSchema":{"type":"object","properties":{"files":{"type":"array","items":{"type":"string"}},"dataset_id":{"type":"integer"},"rebuild_parameters":{"type":"boolean"}},"required":["files"],"additionalProperties":false}},
    {"type":"function","name":"xray_navigate","description":"Show a spectrum, processing stage, fitting step or plot in the main window. Navigation is available in review mode. Select a catalog spectrum by exact path; select a fitting preview by dataset_id. Valid plots: k, r, q, k+r, mu, normalized_mu, flat_mu.","inputSchema":{"type":"object","properties":{"stage":{"type":"string","enum":["data","normalize","background","transform","fit","series","publish"]},"spectrum":{"type":"string"},"dataset_id":{"type":"integer"},"fit_step":{"type":"string","enum":["structure","calculate","paths","model","results"]},"plot":{"type":"string"}},"additionalProperties":false}},
    {"type":"function","name":"xray_set_fit_ranges","description":"Edit the fit ranges and display their live spectrum preview. In multiple-spectrum mode dataset_id is mandatory; each spectrum keeps its own ranges. Undoable. fitspace values use the exact enum spelling from state.","inputSchema":{"type":"object","properties":{"dataset_id":{"type":"integer"},"ranges":{"type":"object"}},"required":["ranges"],"additionalProperties":false}},
    {"type":"function","name":"xray_set_fit_parameter","description":"Change an existing fit parameter value and show the model editor. For a local parameter specify dataset_id. For a global parameter omit dataset_id. Preserves bounds, expressions and global/local assignments. Undoable.","inputSchema":{"type":"object","properties":{"dataset_id":{"type":"integer"},"name":{"type":"string"},"value":{"type":"number"}},"required":["name","value"],"additionalProperties":false}},

        {"type":"function","name":"xray_get_state","description":"Read current rexafs screen, per-spectrum processing settings, fit inputs and recorded results. Returns job state; do not claim completion while processing or fitting is running.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}},
        {"type":"function","name":"xray_set_processing","description":"Update requested normalization, AUTOBK or transform settings on the current spectrum only. The app validates and processes the proposal before applying it. Available only when Allow changes is enabled; undoable.","inputSchema":{"type":"object","properties":{"spectrum":{"type":"string","description":"Exact current_spectrum path from xray_get_state"},"changes":{"type":"object","description":"PipelineParams field names mapped to numeric values, enum names, or null for Auto. Import settings cannot be changed."}},"required":["spectrum","changes"],"additionalProperties":false}},
        {"type":"function","name":"xray_run_fit","description":"Run the currently configured fit, including per-spectrum paths and global/local parameters. Waits for completion. Does not invent or add paths.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}
       ])
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn assistant_resolved_model_labels() {
        assert_eq!(
            resolved_model_label(&[], None),
            ("Automatic · Codex default".into(), None)
        );
        let models = vec![Model {
            model: "available".into(),
            display_name: "Available Model".into(),
            default_reasoning_effort: None,
            supported_reasoning_efforts: vec![],
            hidden: false,
        }];
        assert_eq!(
            resolved_model_label(&models, None),
            ("Automatic · Available Model".into(), None)
        );
        assert_eq!(
            resolved_model_label(&models, Some("available")),
            ("Available Model".into(), None)
        );
        assert_eq!(
            resolved_model_label(&models, Some("missing")),
            (
                "Available Model".into(),
                Some("Saved model missing unavailable · using Available Model".into())
            )
        );
        assert_eq!(
            resolved_model_label(&[], Some("missing")),
            (
                "Codex default".into(),
                Some("Saved model missing unavailable · using Codex default".into())
            )
        );
    }

    #[test]
    fn assistant_effort_choices_have_exactly_one_selection() {
        let mut model = Model {
            model: "example".into(),
            display_name: "Example".into(),
            default_reasoning_effort: Some("medium".into()),
            supported_reasoning_efforts: ["high", "low", "xhigh", "medium", "high", ""]
                .into_iter()
                .map(|value| EffortOption {
                    reasoning_effort: value.into(),
                })
                .collect(),
            hidden: false,
        };
        let defaults = effort_choices(Some(&model), None);
        assert_eq!(
            defaults,
            vec![
                (None, "Model default (Medium)".into(), true),
                (Some("low".into()), "Low".into(), false),
                (Some("medium".into()), "Medium".into(), false),
                (Some("high".into()), "High".into(), false),
                (Some("xhigh".into()), "Extra high".into(), false),
            ]
        );
        for preference in [
            None,
            Some("low"),
            Some("medium"),
            Some("high"),
            Some("xhigh"),
            Some("unknown"),
            Some(""),
        ] {
            let choices = effort_choices(Some(&model), preference);
            assert_eq!(choices.iter().filter(|choice| choice.2).count(), 1);
        }
        let explicit_default = effort_choices(Some(&model), Some("medium"));
        assert!(!explicit_default[0].2);
        assert!(explicit_default[2].2);
        assert!(effort_choices(Some(&model), Some("xhigh"))[4].2);
        model
            .supported_reasoning_efforts
            .retain(|e| e.reasoning_effort != "xhigh");
        let changed = effort_choices(Some(&model), Some("xhigh"));
        assert_eq!(changed, defaults[..4]);
        assert_eq!(selected_effort(Some(&model), Some("xhigh")), Some("medium"));
        model.default_reasoning_effort = None;
        assert_eq!(effort_choices(Some(&model), None)[0].1, "Model default");
        assert_eq!(selected_effort(Some(&model), None), None);
        model.supported_reasoning_efforts.clear();
        assert_eq!(
            effort_choices(Some(&model), Some("xhigh")),
            vec![(None, "Model default".into(), true)]
        );
        assert_eq!(selected_effort(Some(&model), Some("xhigh")), None);
    }

    #[test]
    fn assistant_effort_without_catalog_matches_turn() {
        assert_eq!(
            effort_choices(None, None),
            vec![(None, "Model default".into(), true)]
        );
        assert_eq!(
            effort_choices(None, Some("low")),
            vec![
                (None, "Model default".into(), false),
                (Some("low".into()), "Low".into(), true),
            ]
        );
        assert_eq!(selected_effort(None, Some("low")), Some("low"));
        assert_eq!(selected_effort(None, None), None);
        assert_eq!(selected_effort(None, Some("")), None);
        for preference in [None, Some(""), Some("low"), Some("customLevel")] {
            let choices = effort_choices(None, preference);
            let selected: Vec<_> = choices.iter().filter(|choice| choice.2).collect();
            assert_eq!(selected.len(), 1);
            let effort = selected_effort(None, preference);
            assert_eq!(selected[0].0.as_deref(), effort);
            let params = turn_params("thread", vec![], None, effort);
            assert_eq!(
                params.get("effort"),
                effort.map(|value| json!(value)).as_ref()
            );
        }
    }

    #[test]
    fn assistant_effort_labels_preserve_unknown_values() {
        for (value, label) in [
            ("low", "Low"),
            ("medium", "Medium"),
            ("high", "High"),
            ("xhigh", "Extra high"),
            ("customLevel", "CustomLevel"),
            ("élevé", "Élevé"),
            ("", ""),
        ] {
            assert_eq!(effort_label(value), label);
        }
        let model = Model {
            model: "example".into(),
            display_name: "Example".into(),
            default_reasoning_effort: Some("customLevel".into()),
            supported_reasoning_efforts: vec![EffortOption {
                reasoning_effort: "customLevel".into(),
            }],
            hidden: false,
        };
        assert_eq!(
            effort_choices(Some(&model), Some("customLevel")),
            vec![
                (None, "Model default (CustomLevel)".into(), false),
                (Some("customLevel".into()), "CustomLevel".into(), true),
            ]
        );
    }

    #[test]
    fn assistant_account_protocol() -> Result<(), String> {
        assert_eq!(
            account_label(&json!({"account":null,"requiresOpenaiAuth":true}))?,
            None
        );
        assert_eq!(
            account_label(&json!({"account":null,"requiresOpenaiAuth":false}))?,
            None
        );
        assert_eq!(
            account_label(&json!({"account":{"type":"apiKey"},"requiresOpenaiAuth":true}))?
                .as_deref(),
            Some("API key")
        );
        assert_eq!(account_label(&json!({"account":{"type":"chatgpt","email":"test@example.com","planType":"plus"},"requiresOpenaiAuth":true}))?.as_deref(), Some("ChatGPT · test@example.com · plus"));
        assert_eq!(account_label(&json!({"account":{"type":"chatgpt","email":null,"planType":"pro"},"requiresOpenaiAuth":true}))?.as_deref(), Some("ChatGPT · pro"));
        assert_eq!(
            account_label(&json!({"account":{"type":"future"}}))?.as_deref(),
            Some("Signed in")
        );
        assert!(account_label(&json!({})).is_err());
        assert!(account_label(&json!({"account":false})).is_err());
        Ok(())
    }

    #[test]
    fn assistant_model_protocol_and_turn_preferences() -> Result<(), String> {
        // ModelListResponse / Model from CLI 0.153.4. IDs and display names
        // deliberately differ from the model slug that turn/start accepts.
        let fixture = json!({"data":[{
            "id":"catalog-id","model":"latest-model","displayName":"Latest Model",
            "upgrade":null,"upgradeInfo":null,"availabilityNux":null,"description":"Example",
            "modelSpecialty":null,"hidden":false,
            "supportedReasoningEfforts":[{"reasoningEffort":"medium","description":"Balanced"},{"reasoningEffort":"high","description":"Thorough"}],
            "defaultReasoningEffort":"medium","inputModalities":["text","image"],
            "supportsPersonality":true,"multiAgentVersion":null,"additionalSpeedTiers":[],
            "serviceTiers":[],"defaultServiceTier":null,"isDefault":false
        }],"nextCursor":"page-two"});
        let page = model_page(&fixture)?;
        assert_eq!(page.next_cursor.as_deref(), Some("page-two"));
        let model = selected_model(&page.data, None).ok_or("Missing model")?;
        assert_eq!(model.model, "latest-model");
        assert_eq!(model.display_name, "Latest Model");
        let mut ordered = fixture.clone();
        let mut second = fixture["data"][0].clone();
        second["model"] = json!("saved-model");
        second["isDefault"] = json!(true);
        ordered["data"] = json!([fixture["data"][0], second]);
        let ordered = model_page(&ordered)?;
        assert_eq!(
            selected_model(&ordered.data, None).map(|m| m.model.as_str()),
            Some("latest-model")
        );
        assert_eq!(
            selected_model(&ordered.data, Some("saved-model")).map(|m| m.model.as_str()),
            Some("saved-model")
        );
        assert_eq!(selected_effort(Some(model), None), Some("medium"));
        assert_eq!(selected_effort(Some(model), Some("high")), Some("high"));
        assert_eq!(selected_effort(Some(model), Some("xhigh")), Some("medium"));
        assert_eq!(
            selected_model(&page.data, Some("removed-model")).map(|m| m.model.as_str()),
            Some("latest-model")
        );
        let params = turn_params("thread", vec![], Some(&model.model), Some("high"));
        assert_eq!(params["model"], "latest-model");
        assert_eq!(params["effort"], "high");
        assert_eq!(params["summary"], "detailed");
        let changed = turn_params("thread", vec![], Some("another-model"), Some("low"));
        assert_eq!(changed["model"], "another-model");
        assert_eq!(changed["effort"], "low");
        assert_eq!(changed["threadId"], params["threadId"]);
        let mut hidden = fixture.clone();
        hidden["data"][0]["hidden"] = json!(true);
        assert!(model_page(&hidden)?.data.is_empty());
        let empty = model_page(&json!({"data":[],"nextCursor":null}))?;
        assert!(selected_model(&empty.data, Some("saved-model")).is_none());
        assert_eq!(selected_effort(None, None), None);
        let mut without_default = fixture.clone();
        without_default["data"][0]["defaultReasoningEffort"] = Value::Null;
        let without_default = model_page(&without_default)?;
        assert_eq!(selected_effort(without_default.data.first(), None), None);
        let omitted = turn_params("thread", vec![], None, None);
        assert!(omitted.get("model").is_none());
        assert!(omitted.get("effort").is_none());
        assert_eq!(omitted["summary"], "detailed");
        assert!(model_page(&json!({"data":[{"id":"incomplete"}]})).is_err());
        assert!(model_page(&json!({})).is_err());
        Ok(())
    }
    #[test]
    fn device_code_protocol_does_not_read_credentials() {
        let init = initialize(1);
        assert_eq!(init["params"]["capabilities"]["experimentalApi"], true);
        assert_eq!(dynamic_tools().as_array().unwrap().len(), 12);
    }
    #[test]
    #[ignore = "requires an installed Codex CLI; reads account status without starting a model turn"]
    fn installed_codex_auth_handshake() {
        let c = Client::start().unwrap();
        c.send(initialize(1)).unwrap();
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(30);
        let mut account = false;
        while std::time::Instant::now() < deadline {
            for msg in c.drain() {
                let v = msg.unwrap();
                if v["id"] == 1 {
                    assert!(v.get("error").is_none(), "initialization failed");
                    c.send(json!({"method":"initialized","params":{}})).unwrap();
                    c.send(json!({"id":2,"method":"account/read","params":{"refreshToken":false}}))
                        .unwrap();
                }
                if v["id"] == 2 {
                    assert!(v.get("error").is_none(), "account read failed");
                    account = true;
                }
            }
            if account {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(40));
        }
        assert!(account, "account status timed out");
    }
}
