//! Optional Codex app-server transport. Authentication stays inside Codex.
use serde_json::{Value, json};
use std::{
    collections::VecDeque,
    ffi::OsString,
    io::{BufRead, BufReader, Read, Write},
    path::{Path, PathBuf},
    process::{Child, Command, Stdio},
    sync::{Arc, Condvar, Mutex, mpsc},
    time::Duration,
};

/// v2 GetAccountResponse / Account, generated by `codex app-server generate-ts`.
/// Presence of an account indicates authentication; requiresOpenaiAuth does not.
pub(crate) fn account_label(result: &Value) -> Result<Option<String>, String> {
    let account = result
        .get("account")
        .ok_or("Missing Codex account response")?;
    if account.is_null() {
        return Ok(None);
    }
    if !account.is_object() {
        return Err("Invalid Codex account response".into());
    }
    let label = match account["type"].as_str() {
        Some("apiKey") => "API key".into(),
        Some("chatgpt") => {
            let mut parts = vec!["ChatGPT"];
            for key in ["email", "planType"] {
                if let Some(value) = account[key].as_str().filter(|s| !s.is_empty()) {
                    parts.push(value);
                }
            }
            parts.join(" · ")
        }
        _ => "Signed in".into(),
    };
    Ok(Some(label))
}

#[derive(Clone, Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct Model {
    pub model: String,
    pub display_name: String,
    #[serde(default)]
    pub default_reasoning_effort: Option<String>,
    #[serde(default)]
    pub supported_reasoning_efforts: Vec<EffortOption>,
    #[serde(default)]
    pub hidden: bool,
}

#[derive(Clone, Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct EffortOption {
    pub reasoning_effort: String,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct ModelPage {
    pub data: Vec<Model>,
    pub next_cursor: Option<String>,
}

pub(crate) fn model_page(result: &Value) -> Result<ModelPage, String> {
    let mut page: ModelPage = serde_json::from_value(result.clone())
        .map_err(|e| format!("Invalid Codex model list: {e}"))?;
    page.data.retain(|m| !m.hidden && !m.model.is_empty());
    Ok(page)
}

pub(crate) fn selected_model<'a>(
    models: &'a [Model],
    preferred: Option<&str>,
) -> Option<&'a Model> {
    models
        .iter()
        .find(|m| Some(m.model.as_str()) == preferred)
        .or_else(|| models.first())
}

pub(crate) fn selected_effort<'a>(
    model: Option<&'a Model>,
    preferred: Option<&'a str>,
) -> Option<&'a str> {
    preferred
        .filter(|effort| {
            !effort.is_empty()
                && model.is_none_or(|m| {
                    m.supported_reasoning_efforts
                        .iter()
                        .any(|e| e.reasoning_effort == *effort)
                })
        })
        .or_else(|| model.and_then(|m| m.default_reasoning_effort.as_deref()))
}

/// Describe the same catalog fallback used for turn submission, retaining a
/// warning when a saved preference no longer names an available model.
pub(crate) fn resolved_model_label(
    models: &[Model],
    preferred: Option<&str>,
) -> (String, Option<String>) {
    let resolved = selected_model(models, preferred)
        .map(|m| m.display_name.as_str())
        .unwrap_or("Codex default");
    let warning = preferred
        .filter(|name| !models.iter().any(|m| m.model == *name))
        .map(|name| format!("Saved model {name} unavailable · using {resolved}"));
    let label = if preferred.is_none() {
        format!("Automatic · {resolved}")
    } else {
        resolved.to_owned()
    };
    (label, warning)
}

fn effort_label(value: &str) -> String {
    match value {
        "xhigh" => "Extra high".into(),
        _ => {
            let mut chars = value.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_uppercase().collect::<String>() + chars.as_str()
            })
        }
    }
}

/// Model-default first, followed by supported levels in increasing effort order
/// (unknown levels retain catalog order). None or an unsupported preference
/// selects only model-default; explicit preferences select only their own level.
/// Without a catalog model, retain a non-empty preference as the selected level
/// sent with the turn; otherwise select model-default and omit the effort.
pub(crate) fn effort_choices(
    model: Option<&Model>,
    preferred: Option<&str>,
) -> Vec<(Option<String>, String, bool)> {
    let mut levels: Vec<&str> = Vec::new();
    if let Some(model) = model {
        for option in &model.supported_reasoning_efforts {
            let value = option.reasoning_effort.as_str();
            if !value.is_empty() && !levels.contains(&value) {
                levels.push(value);
            }
        }
    } else if let Some(value) = preferred.filter(|value| !value.is_empty()) {
        levels.push(value);
    }
    levels.sort_by_key(|value| {
        ["low", "medium", "high", "xhigh"]
            .iter()
            .position(|known| known == value)
            .unwrap_or(4)
    });
    let preferred = preferred.filter(|value| levels.contains(value));
    let default_label = model
        .and_then(|m| m.default_reasoning_effort.as_deref())
        .filter(|value| !value.is_empty())
        .map(|value| format!("Model default ({})", effort_label(value)))
        .unwrap_or_else(|| "Model default".into());
    let mut choices = vec![(None, default_label, preferred.is_none())];
    choices.extend(levels.into_iter().map(|value| {
        (
            Some(value.to_owned()),
            effort_label(value),
            preferred == Some(value),
        )
    }));
    choices
}

pub(crate) fn turn_params(
    thread: &str,
    input: Vec<Value>,
    model: Option<&str>,
    effort: Option<&str>,
) -> Value {
    let mut params = json!({"threadId":thread,"input":input,"summary":"detailed"});
    if let Some(effort) = effort {
        params["effort"] = json!(effort);
    }
    if let Some(model) = model {
        params["model"] = json!(model);
    }
    params
}
pub(crate) const INSTALL_URL: &str = "https://learn.chatgpt.com/docs/codex/cli#getting-started";

#[derive(Debug)]
pub(crate) enum StartError {
    NotInstalled,
    Failed(String),
}

impl std::fmt::Display for StartError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotInstalled => f.write_str("Codex CLI was not found on this computer."),
            Self::Failed(message) => f.write_str(message),
        }
    }
}

impl From<String> for StartError {
    fn from(message: String) -> Self {
        Self::Failed(message)
    }
}

pub(crate) struct Client {
    child: Child,
    tx: mpsc::Sender<Value>,
    rx: mpsc::Receiver<Result<Value, String>>,
    pub directory: PathBuf,
}

/// Retain a bounded local diagnostic, without writing Codex logs into a project.
#[derive(Default)]
struct ErrorOutput {
    tail: VecDeque<u8>,
    finished: bool,
}
type Diagnostics = Arc<(Mutex<ErrorOutput>, Condvar)>;

fn capture_errors(mut reader: impl Read, diagnostics: Diagnostics) {
    let mut bytes = [0; 1024];
    while let Ok(count) = reader.read(&mut bytes) {
        if count == 0 {
            break;
        }
        let mut output = diagnostics.0.lock().unwrap_or_else(|e| e.into_inner());
        output.tail.extend(&bytes[..count]);
        let excess = output.tail.len().saturating_sub(4096);
        output.tail.drain(..excess);
    }
    diagnostics
        .0
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .finished = true;
    diagnostics.1.notify_all();
}

fn connection_error(message: &str, diagnostics: &Diagnostics) -> String {
    // stdout can close just before the stderr reader sees the final message.
    // Never wait indefinitely for a child that closes only one of its pipes.
    let output = diagnostics.0.lock().unwrap_or_else(|e| e.into_inner());
    let (output, _) = diagnostics
        .1
        .wait_timeout_while(output, Duration::from_millis(100), |o| !o.finished)
        .unwrap_or_else(|e| e.into_inner());
    let bytes: Vec<_> = output.tail.iter().copied().collect();
    let text = String::from_utf8_lossy(&bytes);
    let detail: String = text
        .lines()
        .rev()
        .find(|line| !line.trim().is_empty())
        .unwrap_or_default()
        .trim()
        .chars()
        .filter(|c| !c.is_control())
        .take(300)
        .collect();
    if detail.is_empty() {
        message.to_owned()
    } else {
        format!("{message}: {detail}")
    }
}

fn client_flags(web_search: bool, extended: bool) -> Vec<String> {
    let mut flags = vec![
        "-c".into(),
        format!("features.shell_tool={extended}"),
        "-c".into(),
        format!("features.unified_exec={extended}"),
        "-c".into(),
        "features.apps=false".into(),
        "-c".into(),
        "features.multi_agent=false".into(),
    ];
    if !web_search {
        flags.extend(["-c".into(), "web_search=\"disabled\"".into()]);
    }
    flags.push("app-server".into());
    flags
}

pub(crate) fn access_thread_params(directory: &Path, extended: bool) -> Value {
    json!({"cwd":directory,"runtimeWorkspaceRoots":[directory],
        "sandbox":if extended {"workspace-write"} else {"read-only"},
        "approvalPolicy":if extended {"untrusted"} else {"never"},
        "approvalsReviewer":"user","ephemeral":true,"selectedCapabilityRoots":[],
        "config":{"mcp_servers":{},"sandbox_workspace_write":{
            "writable_roots":[directory],"network_access":extended,
            "exclude_tmpdir_env_var":true,"exclude_slash_tmp":true}}})
}

/// v2 ThreadResumeParams: threadId plus the same explicit access overrides as
/// thread/start. In particular, a saved thread cannot restore Extended access
/// without the current session's consent. Generated with Codex app-server.
pub(crate) fn resume_thread_params(directory: &Path, extended: bool, thread: &str) -> Value {
    let mut params = access_thread_params(directory, extended);
    if let Some(object) = params.as_object_mut() {
        object.remove("ephemeral");
        object.remove("selectedCapabilityRoots");
        object.insert("threadId".into(), thread.into());
    }
    params
}

#[derive(Clone, Debug, PartialEq)]
pub(crate) struct CommandApproval {
    pub id: Value,
    pub thread: String,
    pub turn: String,
    pub command: String,
    pub cwd: PathBuf,
}
/// v2 CommandExecutionRequestApprovalParams, including opaque JSON-RPC ids.
pub(crate) fn command_approval(v: &Value) -> Result<CommandApproval, String> {
    if v["method"] != "item/commandExecution/requestApproval" {
        return Err("Not a command approval request".into());
    }
    let id = v
        .get("id")
        .filter(|id| id.is_string() || id.is_i64() || id.is_u64())
        .ok_or("Missing approval request id")?
        .clone();
    let p = &v["params"];
    // A reason may request execution outside the sandbox. Fail closed on any
    // non-null reason, as well as network policy, stdin, or extra permissions.
    if p.get("kind").is_some_and(|k| k != "command")
        || p.get("reason").is_some_and(|reason| !reason.is_null())
        || p.get("additionalPermissions").is_some_and(|p| !p.is_null())
        || p.get("networkApprovalContext")
            .is_some_and(|p| !p.is_null())
    {
        return Err("Only individual workspace command approvals are supported".into());
    }
    if let Some(decisions) = p["availableDecisions"].as_array()
        && !decisions.iter().any(|d| d == "accept")
    {
        return Err("This command does not offer a one-time approval".into());
    }
    let field = |key: &str| {
        p[key]
            .as_str()
            .filter(|s| !s.is_empty())
            .map(str::to_owned)
            .ok_or_else(|| format!("Missing approval {key}"))
    };
    Ok(CommandApproval {
        id,
        thread: field("threadId")?,
        turn: field("turnId")?,
        command: field("command")?,
        cwd: field("cwd")?.into(),
    })
}

pub(crate) fn approval_response(id: Value, allow: bool) -> Value {
    json!({"id":id,"result":{"decision":if allow {"accept"} else {"decline"}}})
}

pub(crate) fn command_outcome(v: &Value) -> Option<String> {
    let item = &v["params"]["item"];
    if v["method"] != "item/completed" || item["type"] != "commandExecution" {
        return None;
    }
    let output = item["aggregatedOutput"]
        .as_str()
        .unwrap_or("")
        .lines()
        .take(5)
        .collect::<Vec<_>>()
        .join("\n")
        .chars()
        .take(1200)
        .collect::<String>();
    Some(format!(
        "Command {} · exit {}\n{}\n{}",
        item["status"].as_str().unwrap_or("completed"),
        item["exitCode"],
        item["command"].as_str().unwrap_or(""),
        output
    ))
}
impl Drop for Client {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
        let _ = std::fs::remove_dir_all(&self.directory);
    }
}
impl Client {
    pub fn start(web_search: bool, extended: bool) -> Result<Self, String> {
        let executable = executable().map_err(|e| e.to_string())?;
        let path = std::env::join_paths(search_directories()).map_err(|e| e.to_string())?;
        let directory = std::env::temp_dir().join(format!(
            "rexafs-assistant-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis()
        ));
        let mut builder = std::fs::DirBuilder::new();
        #[cfg(unix)]
        {
            use std::os::unix::fs::DirBuilderExt;
            builder.mode(0o700);
        }
        builder.create(&directory).map_err(|e| e.to_string())?;
        let result = Self::launch(executable, path, directory.clone(), web_search, extended);
        if result.is_err() {
            let _ = std::fs::remove_dir_all(&directory);
        }
        result
    }

    fn launch(
        executable: PathBuf,
        path: OsString,
        directory: PathBuf,
        web_search: bool,
        extended: bool,
    ) -> Result<Self, String> {
        let mut command = Command::new(executable);
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            command.creation_flags(0x08000000); // CREATE_NO_WINDOW
        }
        let mut child = command
            .args(client_flags(web_search, extended))
            // Finder does not inherit interactive-shell PATH additions. The
            // discovered npm/Bun launcher may still need a separately installed node.
            .env("PATH", path)
            .current_dir(&directory)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| format!("Could not start Codex: {e}"))?;
        let mut stdin = child.stdin.take().ok_or("Codex stdin unavailable")?;
        let stdout = child.stdout.take().ok_or("Codex stdout unavailable")?;
        let stderr = child.stderr.take().ok_or("Codex stderr unavailable")?;
        let diagnostics = Diagnostics::default();
        let capture = diagnostics.clone();
        std::thread::spawn(move || capture_errors(stderr, capture));
        let (tx, outgoing) = mpsc::channel::<Value>();
        let (incoming, rx) = mpsc::channel();
        let errors = incoming.clone();
        let write_diagnostics = diagnostics.clone();
        std::thread::spawn(move || {
            while let Ok(v) = outgoing.recv() {
                if let Err(e) = writeln!(stdin, "{v}").and_then(|_| stdin.flush()) {
                    let _ = errors.send(Err(connection_error(
                        &format!("Codex connection closed: {e}"),
                        &write_diagnostics,
                    )));
                    break;
                }
            }
        });
        std::thread::spawn(move || {
            for line in BufReader::new(stdout).lines() {
                match line {
                    Ok(line) => match serde_json::from_str(&line) {
                        Ok(v) => {
                            if incoming.send(Ok(v)).is_err() {
                                return;
                            }
                        }
                        Err(_) => {
                            let _ = incoming
                                .send(Err("Codex returned an invalid protocol message".into()));
                        }
                    },
                    Err(e) => {
                        let _ = incoming.send(Err(e.to_string()));
                        return;
                    }
                }
            }
            let _ = incoming.send(Err(connection_error("Codex disconnected", &diagnostics)));
        });
        Ok(Self {
            child,
            tx,
            rx,
            directory,
        })
    }
    pub fn send(&self, v: Value) -> Result<(), String> {
        self.tx.send(v).map_err(|_| "Codex disconnected".into())
    }
    pub fn drain(&self) -> Vec<Result<Value, String>> {
        self.rx.try_iter().take(200).collect()
    }
}
/// Discovery only: no subprocess, login, credential access or network request.
pub(crate) fn executable() -> Result<PathBuf, StartError> {
    let mut candidates = candidate_paths(cfg!(windows), search_directories());
    if cfg!(target_os = "macos") {
        if let Some(home) = crate::settings::home_dir() {
            candidates.push(home.join("Applications/Codex.app/Contents/Resources/codex"));
        }
        candidates.push("/Applications/Codex.app/Contents/Resources/codex".into());
    }
    find_executable(
        crate::settings::env_var_os("CODEX").map(PathBuf::from),
        candidates,
    )
}

fn candidate_paths(windows: bool, directories: Vec<PathBuf>) -> Vec<PathBuf> {
    let names: &[&str] = if windows {
        &["codex.exe", "codex.cmd"]
    } else {
        &["codex"]
    };
    directories
        .into_iter()
        .flat_map(|directory| names.iter().map(move |name| directory.join(name)))
        .collect()
}

/// Preserve absolute PATH entries, then add known installation prefixes. Do not
/// execute shell startup files or change the parent process's environment.
fn search_directories() -> Vec<PathBuf> {
    let path = std::env::var_os("PATH")
        .map(|p| std::env::split_paths(&p).collect())
        .unwrap_or_default();
    executable_directories(
        cfg!(windows),
        path,
        crate::settings::home_dir().as_deref(),
        std::env::var_os("LOCALAPPDATA").as_deref().map(Path::new),
        std::env::var_os("APPDATA").as_deref().map(Path::new),
        std::env::var_os("CODEX_INSTALL_DIR")
            .as_deref()
            .map(Path::new),
    )
}

fn executable_directories(
    windows: bool,
    mut directories: Vec<PathBuf>,
    home: Option<&Path>,
    local_app_data: Option<&Path>,
    app_data: Option<&Path>,
    install_dir: Option<&Path>,
) -> Vec<PathBuf> {
    if let Some(path) = install_dir.filter(|p| !p.as_os_str().is_empty()) {
        directories.insert(0, path.to_owned());
    }
    if windows {
        if let Some(local) = local_app_data {
            directories.push(local.join("Programs/OpenAI/Codex/bin"));
        } else if let Some(home) = home {
            directories.push(home.join("AppData/Local/Programs/OpenAI/Codex/bin"));
        }
        if let Some(roaming) = app_data {
            directories.push(roaming.join("npm"));
        } else if let Some(home) = home {
            directories.push(home.join("AppData/Roaming/npm"));
        }
    }
    if let Some(home) = home {
        directories.extend([
            home.join(".bun/bin"),
            home.join(".local/bin"),
            home.join(".npm-global/bin"),
        ]);
    }
    if !windows {
        if let Some(home) = home {
            directories.extend([
                home.join(".nix-profile/bin"),
                home.join(".volta/bin"),
                home.join(".local/share/mise/shims"),
            ]);
            if let Some(user) = home.file_name() {
                directories.push(Path::new("/etc/profiles/per-user").join(user).join("bin"));
            }
        }
        directories.extend([
            PathBuf::from("/opt/homebrew/bin"),
            PathBuf::from("/usr/local/bin"),
            PathBuf::from("/nix/var/nix/profiles/default/bin"),
            PathBuf::from("/usr/bin"),
            PathBuf::from("/bin"),
        ]);
    }
    let mut unique = Vec::new();
    for directory in directories {
        // Neither discovery nor the child should search its temporary workspace.
        if directory.is_absolute() && !unique.contains(&directory) {
            unique.push(directory);
        }
    }
    unique
}

fn usable_executable(path: &Path) -> bool {
    let Ok(metadata) = path.metadata() else {
        return false;
    };
    if !metadata.is_file() {
        return false;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        metadata.permissions().mode() & 0o111 != 0
    }
    #[cfg(not(unix))]
    {
        true
    }
}

fn find_executable(
    override_path: Option<PathBuf>,
    candidates: Vec<PathBuf>,
) -> Result<PathBuf, StartError> {
    if let Some(path) = override_path {
        if !usable_executable(&path) {
            return Err(StartError::Failed(format!(
                "REXAFS_CODEX (or XTS_CODEX) points to an unavailable executable: {}. Update or remove this override and restart rexafs.",
                path.display()
            )));
        }
        // Resolve overrides before the child changes into its private working directory.
        return std::fs::canonicalize(path).map_err(|e| e.to_string().into());
    }
    candidates
        .into_iter()
        .find(|p| usable_executable(p))
        .ok_or(StartError::NotInstalled)
}
pub(crate) fn initialize(id: u64) -> Value {
    json!({"id":id,"method":"initialize","params":{"clientInfo":{"name":"rexafs","title":"rexafs","version":env!("CARGO_PKG_VERSION")},"capabilities":{"experimentalApi":true}}})
}
pub(crate) fn dynamic_tools() -> Value {
    json!([
    {"type":"function","name":"xray_fetch_structure","description":"After stating the exact source, request user confirmation to download an HTTPS CIF URL or load a CIF path inside the temporary assistant workspace. Requires Edit analysis. Provide exactly one of url or path; returns formula, cell, number of sites and saved path.","inputSchema":{"type":"object","properties":{"url":{"type":"string"},"path":{"type":"string"},"label":{"type":"string"}},"oneOf":[{"required":["url"]},{"required":["path"]}],"additionalProperties":false}},
    {"type":"function","name":"xray_set_layout","description":"Change file browser/inspector visibility and current/marked plot scope only. Review mode allows these presentation changes.","inputSchema":{"type":"object","properties":{"file_browser":{"type":"boolean"},"inspector":{"type":"boolean"},"plot_scope":{"type":"string","enum":["current","marked"]}},"additionalProperties":false}},
    {"type":"function","name":"xray_get_plots","description":"Inspect the current processing stage or fit results: returns fresh plots plus resolved numerical settings. Navigate to Normalize, Background and Transform and inspect each before running a fit. Respects the Plots switch.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}},
    {"type":"function","name":"xray_search_structures","description":"Search the curated reference-structure library and display Structure. Returns candidates with stable ids; do not infer metallic composition merely from an element name.","inputSchema":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"],"additionalProperties":false}},
    {"type":"function","name":"xray_choose_structure","description":"Choose a returned curated structure id; display its crystal and 8 Å cluster preview. Returns absorber, edge and site information for inspection.","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"],"additionalProperties":false}},
    {"type":"function","name":"xray_calculate_paths","description":"Run the selected FEFF/ReFEFF backend using the inspected structure, absorber and cluster. Shows Calculate, waits for completion, then shows Paths. Reuse suitable calculated paths; do not duplicate calculations without reason.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}},
    {"type":"function","name":"xray_select_paths","description":"Assign an explicit list of already calculated FEFF files. For multiple-spectrum fits dataset_id is required. Preserves existing expressions; rebuild_parameters=true explicitly regenerates the parameter template and should only be used for a new model.","inputSchema":{"type":"object","properties":{"files":{"type":"array","items":{"type":"string"}},"dataset_id":{"type":"integer"},"rebuild_parameters":{"type":"boolean"}},"required":["files"],"additionalProperties":false}},
    {"type":"function","name":"xray_navigate","description":"Show a spectrum, processing stage, fitting step or plot in the main window. Navigation is available in review mode. Select any imported or catalog spectrum by group_id from the overview; alternatively use an exact catalog path or a fitting preview dataset_id. Use only one selector. Valid plots: k, r, q, k+r, mu, normalized_mu, flat_mu.","inputSchema":{"type":"object","properties":{"stage":{"type":"string","enum":["data","normalize","background","transform","fit","series","publish"]},"spectrum":{"type":"string"},"group_id":{"type":"string"},"dataset_id":{"type":"integer"},"fit_step":{"type":"string","enum":["structure","calculate","paths","model","results"]},"plot":{"type":"string"}},"additionalProperties":false}},
    {"type":"function","name":"xray_set_fit_ranges","description":"Edit the fit ranges and display their live spectrum preview. In multiple-spectrum mode dataset_id is mandatory; each spectrum keeps its own ranges. Undoable. fitspace values use the exact enum spelling from state.","inputSchema":{"type":"object","properties":{"dataset_id":{"type":"integer"},"ranges":{"type":"object"}},"required":["ranges"],"additionalProperties":false}},
    {"type":"function","name":"xray_set_fit_parameter","description":"Change an existing fit parameter value and show the model editor. For a local parameter specify dataset_id. For a global parameter omit dataset_id. Preserves bounds, expressions and global/local assignments. Undoable.","inputSchema":{"type":"object","properties":{"dataset_id":{"type":"integer"},"name":{"type":"string"},"value":{"type":"number"}},"required":["name","value"],"additionalProperties":false}},

        {"type":"function","name":"xray_get_state","description":"Retrieve only the relevant analysis section: overview (default, 50-group pages), source (header/metadata for one group, 4096-character header pages), processing (exact settings for one group), fit (current model/ranges and calculation state), history (10 historical fits per page), or analysis (LCF/PCA coefficients and scalar results). derived_id selects an imported/result group from overview; omit it for the current group. Use next_offset for pagination. Arrays and original file bytes are not prompt text. Returns job state; do not claim completion while processing or fitting is running.","inputSchema":{"type":"object","properties":{"section":{"type":"string","enum":["overview","source","processing","fit","history","analysis"]},"derived_id":{"type":"integer","minimum":0},"offset":{"type":"integer","minimum":0}},"additionalProperties":false}},
        {"type":"function","name":"xray_set_processing","description":"Update requested normalization, AUTOBK or transform settings on the current spectrum only. The app validates and processes the proposal before applying it. Available only when Edit analysis mode is enabled; undoable.","inputSchema":{"type":"object","properties":{"spectrum":{"type":"string","description":"Exact current_spectrum path from xray_get_state"},"group_id":{"type":"string","description":"Current group_id from overview; required for imported spectra"},"changes":{"type":"object","description":"PipelineParams field names mapped to numeric values, enum names, or null for Auto. Import settings cannot be changed."}},"required":["spectrum","changes"],"additionalProperties":false}},
        {"type":"function","name":"xray_configure_fit","description":"Configure the existing EXAFS model for single (current group) or multiple spectra (explicit group_ids). Undoable; preserves existing dataset paths, expressions, ranges and local values. For a first joint setup, local_parameters lists existing variable names to fit independently per spectrum; other variables are shared. Existing scopes are preserved on subsequent setup. Does not run a fit. Independent batch fits can use single mode, then navigate/inspect/run each requested group.","inputSchema":{"type":"object","properties":{"mode":{"type":"string","enum":["single","multiple"]},"group_ids":{"type":"array","items":{"type":"string"}},"local_parameters":{"type":"array","items":{"type":"string"}}},"required":["mode"],"additionalProperties":false}},
        {"type":"function","name":"xray_run_analysis","description":"Run the GUI's LCF or PCA and show its result. Requires Edit analysis. First navigate to and inspect each requested group's normalized processing, then return to the target. References must be at least two distinct loaded group_ids, excluding the target. LCF uses nonnegative weights bounded by one, sum-to-one by default, no shifts by default. PCA uses the GUI's uncentered training and requires an explicit retained component count. Energy ranges are offsets from E0 in eV (default -20 to +30); chi ranges are absolute k in inverse angstroms (default 3 to 12), with the current plot k-weight. Choose common measured coverage. PCA fractions are squared signal, not chemical concentrations. Returns exact coefficients/scalar diagnostics; spectral arrays remain local.","inputSchema":{"type":"object","properties":{"method":{"type":"string","enum":["lcf","pca"]},"target_group_id":{"type":"string"},"reference_group_ids":{"type":"array","minItems":2,"uniqueItems":true,"items":{"type":"string"}},"space":{"type":"string","enum":["norm","flat","derivative","chi"]},"range":{"type":"array","minItems":2,"maxItems":2,"items":{"type":"number"}},"sum_to_one":{"type":"boolean"},"fit_energy_shifts":{"type":"boolean"},"components":{"type":"integer","minimum":1}},"required":["method","target_group_id","reference_group_ids"],"additionalProperties":false}},
        {"type":"function","name":"xray_run_fit","description":"Run the currently configured fit, including per-spectrum paths and global/local parameters. Waits for completion. Does not invent or add paths.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}
       ])
}
#[cfg(test)]
mod tests {
    use super::*;

    fn executable_candidates(
        windows: bool,
        directories: Vec<PathBuf>,
        home: Option<&Path>,
        local: Option<&Path>,
        roaming: Option<&Path>,
        install: Option<&Path>,
    ) -> Vec<PathBuf> {
        candidate_paths(
            windows,
            executable_directories(windows, directories, home, local, roaming, install),
        )
    }
    struct Fixture(PathBuf);
    impl Fixture {
        fn new() -> Self {
            static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
            let path = std::env::temp_dir().join(format!(
                "rexafs-codex-discovery-{}-{}",
                std::process::id(),
                NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
            ));
            std::fs::create_dir(&path).unwrap();
            Self(path)
        }
        fn executable(&self, relative: &str) -> PathBuf {
            let path = self.0.join(relative);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, "test executable fixture").unwrap();
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o700)).unwrap();
            }
            path
        }
    }
    impl Drop for Fixture {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[cfg(unix)]
    fn await_message(client: &Client) -> Vec<Result<Value, String>> {
        let deadline = std::time::Instant::now() + Duration::from_secs(5);
        loop {
            let messages = client.drain();
            if !messages.is_empty() {
                return messages;
            }
            assert!(
                std::time::Instant::now() < deadline,
                "transport did not respond"
            );
            std::thread::sleep(Duration::from_millis(5));
        }
    }

    #[cfg(unix)]
    #[test]
    fn finder_launch_resolves_node_without_reading_shell_profiles() {
        let f = Fixture::new();
        let launcher = f.executable(".bun/bin/codex");
        std::fs::write(&launcher, "#!/usr/bin/env node\n").unwrap();
        let node = f.executable(".nix-profile/bin/node");
        std::fs::write(
            node,
            "#!/bin/sh\nprintf '%s\\n' '{\"id\":1,\"result\":\"profile-node\"}'\nread line\n",
        )
        .unwrap();
        let workspace = f.0.join("assistant-workspace");
        std::fs::create_dir(&workspace).unwrap();
        let directories = executable_directories(
            false,
            vec!["/usr/bin".into(), "/bin".into(), ".".into(), PathBuf::new()],
            Some(&f.0),
            None,
            None,
            None,
        );
        let client = Client::launch(
            launcher,
            std::env::join_paths(&directories).unwrap(),
            workspace.clone(),
            false,
            false,
        )
        .unwrap();
        assert_eq!(
            await_message(&client),
            vec![Ok(json!({"id":1,"result":"profile-node"}))]
        );
        assert!(directories.iter().all(|p| p.is_absolute()));
        assert!(
            directories.contains(
                &Path::new("/etc/profiles/per-user")
                    .join(f.0.file_name().unwrap())
                    .join("bin")
            )
        );
        drop(client);
        assert!(!workspace.exists());
        // Existing absolute PATH entries continue to take precedence.
        let preferred = f.executable("preferred/node");
        let directories = executable_directories(
            false,
            vec![
                preferred.parent().unwrap().into(),
                preferred.parent().unwrap().into(),
            ],
            Some(&f.0),
            None,
            None,
            None,
        );
        assert_eq!(directories[0], preferred.parent().unwrap());
        assert_eq!(
            directories
                .iter()
                .filter(|p| *p == preferred.parent().unwrap())
                .count(),
            1
        );
    }

    #[cfg(unix)]
    #[test]
    fn failed_launcher_reports_stderr_instead_of_only_disconnected() {
        let f = Fixture::new();
        let launcher = f.executable("broken-codex");
        std::fs::write(
            &launcher,
            "#!/bin/sh\nprintf '%s\\n' 'env: node: No such file or directory' >&2\nexit 127\n",
        )
        .unwrap();
        let workspace = f.0.join("assistant-workspace");
        std::fs::create_dir(&workspace).unwrap();
        let client = Client::launch(
            launcher,
            OsString::from("/usr/bin:/bin"),
            workspace,
            false,
            false,
        )
        .unwrap();
        assert!(await_message(&client).iter().any(|message| {
            message
                .as_ref()
                .is_err_and(|error| error.contains("env: node: No such file or directory"))
        }));
    }

    #[test]
    fn error_output_is_bounded_and_keeps_the_last_diagnostic() {
        let diagnostics = Diagnostics::default();
        let mut log = vec![b'x'; 16384];
        log.extend_from_slice(b"\nlast error\0\n\n");
        capture_errors(std::io::Cursor::new(log), diagnostics.clone());
        assert_eq!(diagnostics.0.lock().unwrap().tail.len(), 4096);
        assert_eq!(
            connection_error("Codex disconnected", &diagnostics),
            "Codex disconnected: last error"
        );
        let empty = Diagnostics::default();
        capture_errors(std::io::empty(), empty.clone());
        assert_eq!(
            connection_error("Codex disconnected", &empty),
            "Codex disconnected"
        );
    }

    #[test]
    fn discovery_finds_windows_standalone_and_npm_without_updated_path() {
        let f = Fixture::new();
        let local = f.0.join("Local App Data");
        let roaming = f.0.join("Roaming");
        let candidates =
            executable_candidates(true, vec![], Some(&f.0), Some(&local), Some(&roaming), None);
        assert!(matches!(
            find_executable(None, candidates.clone()),
            Err(StartError::NotInstalled)
        ));
        let npm = f.executable("Roaming/npm/codex.cmd");
        assert_eq!(find_executable(None, candidates.clone()).unwrap(), npm);
        let native = f.executable("Local App Data/Programs/OpenAI/Codex/bin/codex.exe");
        assert_eq!(find_executable(None, candidates).unwrap(), native);
        // The extensionless npm shim is a shell script, not a Windows executable.
        f.executable("path/codex");
        let path_native = f.executable("path/codex.exe");
        let path = executable_candidates(true, vec![f.0.join("path")], None, None, None, None);
        assert_eq!(find_executable(None, path).unwrap(), path_native);
    }

    #[test]
    fn explicit_override_wins_and_invalid_override_is_actionable() {
        let f = Fixture::new();
        let first = f.executable("path/codex");
        let custom = f.executable("Custom Install/codex");
        assert_eq!(
            find_executable(Some(custom.clone()), vec![first.clone()]).unwrap(),
            std::fs::canonicalize(custom).unwrap()
        );
        let error = find_executable(Some(f.0.join("missing")), vec![first]).unwrap_err();
        assert!(matches!(error, StartError::Failed(_)));
        assert!(error.to_string().contains("REXAFS_CODEX"));
    }

    #[test]
    fn discovery_respects_path_and_custom_install_directory() {
        let f = Fixture::new();
        let fallback = f.executable(".local/bin/codex");
        let path = f.executable("path/codex");
        let custom = f.executable("custom/codex");
        let candidates = executable_candidates(
            false,
            vec![f.0.join("path")],
            Some(&f.0),
            None,
            None,
            Some(&f.0.join("custom")),
        );
        assert_eq!(find_executable(None, candidates).unwrap(), custom);
        let candidates =
            executable_candidates(false, vec![f.0.join("path")], Some(&f.0), None, None, None);
        assert_eq!(find_executable(None, candidates).unwrap(), path);
        let candidates = executable_candidates(
            false,
            vec![PathBuf::new(), PathBuf::from(".")],
            Some(&f.0),
            None,
            None,
            None,
        );
        assert_eq!(find_executable(None, candidates).unwrap(), fallback);
    }

    #[cfg(unix)]
    #[test]
    fn discovery_skips_directories_and_non_executable_files() {
        let f = Fixture::new();
        let not_executable = f.0.join("codex");
        std::fs::write(&not_executable, "not executable").unwrap();
        assert!(matches!(
            find_executable(None, vec![f.0.clone(), not_executable]),
            Err(StartError::NotInstalled)
        ));
    }

    #[test]
    fn assistant_resume_preserves_current_access_policy_without_start_only_fields() {
        let params =
            resume_thread_params(std::path::Path::new("/workspace"), false, "saved-thread");
        assert_eq!(params["threadId"], "saved-thread");
        assert_eq!(params["sandbox"], "read-only");
        assert_eq!(params["approvalPolicy"], "never");
        assert!(params.get("ephemeral").is_none());
        assert!(params.get("selectedCapabilityRoots").is_none());
        assert_eq!(
            params["config"]["sandbox_workspace_write"]["network_access"],
            false
        );
    }

    #[test]
    fn assistant_command_approval_protocol() {
        let fixture = json!({"id":"approval-4","method":"item/commandExecution/requestApproval","params":{
            "kind":"command","threadId":"thread-1","turnId":"turn-2","itemId":"cmd-3","startedAtMs":123,
            "approvalId":null,"environmentId":null,"command":"curl -o ru.cif https://example.org/ru.cif",
            "cwd":"/tmp/rexafs-workspace","commandActions":[],"additionalPermissions":null,
            "availableDecisions":["accept","acceptForSession","decline","cancel"]}});
        let parsed = command_approval(&fixture).unwrap();
        assert_eq!(parsed.id, "approval-4");
        assert_eq!(parsed.turn, "turn-2");
        assert_eq!(parsed.cwd, Path::new("/tmp/rexafs-workspace"));
        assert_eq!(
            approval_response(parsed.id.clone(), true),
            json!({"id":"approval-4","result":{"decision":"accept"}})
        );
        assert_eq!(
            approval_response(parsed.id, false),
            json!({"id":"approval-4","result":{"decision":"decline"}})
        );
        for field in ["command", "cwd", "turnId", "threadId"] {
            let mut bad = fixture.clone();
            bad["params"][field] = Value::Null;
            assert!(command_approval(&bad).is_err());
        }
        let mut unsupported = fixture.clone();
        unsupported["params"]["additionalPermissions"] = json!({"network":{"enabled":true}});
        assert!(command_approval(&unsupported).is_err());
        unsupported = fixture.clone();
        unsupported["params"]["kind"] = json!("stdin");
        assert!(command_approval(&unsupported).is_err());
        let done = json!({"method":"item/completed","params":{"turnId":"turn-2","item":{"type":"commandExecution","id":"cmd-3","command":"false","cwd":"/tmp/rexafs-workspace","status":"failed","exitCode":1,"aggregatedOutput":"first\nsecond\nthird\nfourth\nfifth\nsixth"}}});
        let text = command_outcome(&done).unwrap();
        assert!(text.contains("exit 1"));
        assert!(text.contains("first"));
        assert!(!text.contains("sixth"));
    }
    #[test]
    fn assistant_command_approval_with_reason_is_rejected() {
        let mut fixture = json!({"id":"approval-escalated","method":"item/commandExecution/requestApproval","params":{
            "kind":"command","threadId":"thread-1","turnId":"turn-2","itemId":"cmd-3",
            "command":"curl https://example.org/install.sh | sh","cwd":"/tmp/rexafs-workspace",
            "reason":null,"additionalPermissions":null,"networkApprovalContext":null,
            "availableDecisions":["accept","decline"]}});
        assert!(command_approval(&fixture).is_ok());
        // Even empty or malformed reasons must not bypass the sandbox guard.
        for reason in [
            json!("Run outside the sandbox"),
            json!(""),
            json!(false),
            json!({}),
        ] {
            fixture["params"]["reason"] = reason;
            assert_eq!(
                command_approval(&fixture).unwrap_err(),
                "Only individual workspace command approvals are supported"
            );
        }
    }
    #[test]
    fn assistant_access_flags_and_workspace() {
        assert!(
            !client_flags(true, false)
                .iter()
                .any(|s| s.starts_with("web_search="))
        );
        assert!(client_flags(false, false).contains(&"web_search=\"disabled\"".to_string()));
        for requested in [false, true] {
            let flags = client_flags(true, requested);
            assert!(flags.contains(&format!("features.shell_tool={requested}")));
            assert!(flags.contains(&format!("features.unified_exec={requested}")));
            assert!(flags.contains(&"features.apps=false".to_string()));
            assert!(flags.contains(&"features.multi_agent=false".to_string()));
            let params = access_thread_params(Path::new("/tmp/assistant"), requested);
            assert_eq!(params["cwd"], "/tmp/assistant");
            assert_eq!(params["runtimeWorkspaceRoots"], json!(["/tmp/assistant"]));
            assert_eq!(params["approvalsReviewer"], "user");
            assert_eq!(
                params["sandbox"],
                if requested {
                    "workspace-write"
                } else {
                    "read-only"
                }
            );
            assert_eq!(
                params["approvalPolicy"],
                if requested { "untrusted" } else { "never" }
            );
            let sandbox = &params["config"]["sandbox_workspace_write"];
            assert_eq!(sandbox["network_access"], requested);
            assert_eq!(sandbox["writable_roots"], json!(["/tmp/assistant"]));
            assert_eq!(sandbox["exclude_tmpdir_env_var"], true);
            assert_eq!(
                params["config"]["sandbox_workspace_write"]["exclude_slash_tmp"],
                true
            );
        }
        let tools = dynamic_tools();
        let fetch = tools
            .as_array()
            .unwrap()
            .iter()
            .find(|t| t["name"] == "xray_fetch_structure")
            .unwrap();
        assert_eq!(
            fetch["inputSchema"]["oneOf"],
            json!([{"required":["url"]},{"required":["path"]}])
        );
    }

    #[test]
    fn assistant_layout_schema_only_exposes_panels_and_scope() {
        let tools = dynamic_tools();
        let layout = tools
            .as_array()
            .expect("tool array")
            .iter()
            .find(|tool| tool["name"] == "xray_set_layout")
            .expect("layout tool");
        let schema = &layout["inputSchema"];
        let properties = schema["properties"].as_object().expect("properties");
        assert_eq!(properties.len(), 3);
        for key in ["file_browser", "inspector", "plot_scope"] {
            assert!(properties.contains_key(key));
        }
        assert_eq!(schema["additionalProperties"], false);
    }

    #[test]
    fn assistant_resolved_model_labels() {
        assert_eq!(
            resolved_model_label(&[], None),
            ("Automatic · Codex default".into(), None)
        );
        let models = vec![Model {
            model: "available".into(),
            display_name: "Available Model".into(),
            default_reasoning_effort: None,
            supported_reasoning_efforts: vec![],
            hidden: false,
        }];
        assert_eq!(
            resolved_model_label(&models, None),
            ("Automatic · Available Model".into(), None)
        );
        assert_eq!(
            resolved_model_label(&models, Some("available")),
            ("Available Model".into(), None)
        );
        assert_eq!(
            resolved_model_label(&models, Some("missing")),
            (
                "Available Model".into(),
                Some("Saved model missing unavailable · using Available Model".into())
            )
        );
        assert_eq!(
            resolved_model_label(&[], Some("missing")),
            (
                "Codex default".into(),
                Some("Saved model missing unavailable · using Codex default".into())
            )
        );
    }

    #[test]
    fn assistant_effort_choices_have_exactly_one_selection() {
        let mut model = Model {
            model: "example".into(),
            display_name: "Example".into(),
            default_reasoning_effort: Some("medium".into()),
            supported_reasoning_efforts: ["high", "low", "xhigh", "medium", "high", ""]
                .into_iter()
                .map(|value| EffortOption {
                    reasoning_effort: value.into(),
                })
                .collect(),
            hidden: false,
        };
        let defaults = effort_choices(Some(&model), None);
        assert_eq!(
            defaults,
            vec![
                (None, "Model default (Medium)".into(), true),
                (Some("low".into()), "Low".into(), false),
                (Some("medium".into()), "Medium".into(), false),
                (Some("high".into()), "High".into(), false),
                (Some("xhigh".into()), "Extra high".into(), false),
            ]
        );
        for preference in [
            None,
            Some("low"),
            Some("medium"),
            Some("high"),
            Some("xhigh"),
            Some("unknown"),
            Some(""),
        ] {
            let choices = effort_choices(Some(&model), preference);
            assert_eq!(choices.iter().filter(|choice| choice.2).count(), 1);
        }
        let explicit_default = effort_choices(Some(&model), Some("medium"));
        assert!(!explicit_default[0].2);
        assert!(explicit_default[2].2);
        assert!(effort_choices(Some(&model), Some("xhigh"))[4].2);
        model
            .supported_reasoning_efforts
            .retain(|e| e.reasoning_effort != "xhigh");
        let changed = effort_choices(Some(&model), Some("xhigh"));
        assert_eq!(changed, defaults[..4]);
        assert_eq!(selected_effort(Some(&model), Some("xhigh")), Some("medium"));
        model.default_reasoning_effort = None;
        assert_eq!(effort_choices(Some(&model), None)[0].1, "Model default");
        assert_eq!(selected_effort(Some(&model), None), None);
        model.supported_reasoning_efforts.clear();
        assert_eq!(
            effort_choices(Some(&model), Some("xhigh")),
            vec![(None, "Model default".into(), true)]
        );
        assert_eq!(selected_effort(Some(&model), Some("xhigh")), None);
    }

    #[test]
    fn assistant_effort_without_catalog_matches_turn() {
        assert_eq!(
            effort_choices(None, None),
            vec![(None, "Model default".into(), true)]
        );
        assert_eq!(
            effort_choices(None, Some("low")),
            vec![
                (None, "Model default".into(), false),
                (Some("low".into()), "Low".into(), true),
            ]
        );
        assert_eq!(selected_effort(None, Some("low")), Some("low"));
        assert_eq!(selected_effort(None, None), None);
        assert_eq!(selected_effort(None, Some("")), None);
        for preference in [None, Some(""), Some("low"), Some("customLevel")] {
            let choices = effort_choices(None, preference);
            let selected: Vec<_> = choices.iter().filter(|choice| choice.2).collect();
            assert_eq!(selected.len(), 1);
            let effort = selected_effort(None, preference);
            assert_eq!(selected[0].0.as_deref(), effort);
            let params = turn_params("thread", vec![], None, effort);
            assert_eq!(
                params.get("effort"),
                effort.map(|value| json!(value)).as_ref()
            );
        }
    }

    #[test]
    fn assistant_effort_labels_preserve_unknown_values() {
        for (value, label) in [
            ("low", "Low"),
            ("medium", "Medium"),
            ("high", "High"),
            ("xhigh", "Extra high"),
            ("customLevel", "CustomLevel"),
            ("élevé", "Élevé"),
            ("", ""),
        ] {
            assert_eq!(effort_label(value), label);
        }
        let model = Model {
            model: "example".into(),
            display_name: "Example".into(),
            default_reasoning_effort: Some("customLevel".into()),
            supported_reasoning_efforts: vec![EffortOption {
                reasoning_effort: "customLevel".into(),
            }],
            hidden: false,
        };
        assert_eq!(
            effort_choices(Some(&model), Some("customLevel")),
            vec![
                (None, "Model default (CustomLevel)".into(), false),
                (Some("customLevel".into()), "CustomLevel".into(), true),
            ]
        );
    }

    #[test]
    fn assistant_account_protocol() -> Result<(), String> {
        assert_eq!(
            account_label(&json!({"account":null,"requiresOpenaiAuth":true}))?,
            None
        );
        assert_eq!(
            account_label(&json!({"account":null,"requiresOpenaiAuth":false}))?,
            None
        );
        assert_eq!(
            account_label(&json!({"account":{"type":"apiKey"},"requiresOpenaiAuth":true}))?
                .as_deref(),
            Some("API key")
        );
        assert_eq!(account_label(&json!({"account":{"type":"chatgpt","email":"test@example.com","planType":"plus"},"requiresOpenaiAuth":true}))?.as_deref(), Some("ChatGPT · test@example.com · plus"));
        assert_eq!(account_label(&json!({"account":{"type":"chatgpt","email":null,"planType":"pro"},"requiresOpenaiAuth":true}))?.as_deref(), Some("ChatGPT · pro"));
        assert_eq!(
            account_label(&json!({"account":{"type":"future"}}))?.as_deref(),
            Some("Signed in")
        );
        assert!(account_label(&json!({})).is_err());
        assert!(account_label(&json!({"account":false})).is_err());
        Ok(())
    }

    #[test]
    fn assistant_model_protocol_and_turn_preferences() -> Result<(), String> {
        // ModelListResponse / Model from CLI 0.153.4. IDs and display names
        // deliberately differ from the model slug that turn/start accepts.
        let fixture = json!({"data":[{
            "id":"catalog-id","model":"latest-model","displayName":"Latest Model",
            "upgrade":null,"upgradeInfo":null,"availabilityNux":null,"description":"Example",
            "modelSpecialty":null,"hidden":false,
            "supportedReasoningEfforts":[{"reasoningEffort":"medium","description":"Balanced"},{"reasoningEffort":"high","description":"Thorough"}],
            "defaultReasoningEffort":"medium","inputModalities":["text","image"],
            "supportsPersonality":true,"multiAgentVersion":null,"additionalSpeedTiers":[],
            "serviceTiers":[],"defaultServiceTier":null,"isDefault":false
        }],"nextCursor":"page-two"});
        let page = model_page(&fixture)?;
        assert_eq!(page.next_cursor.as_deref(), Some("page-two"));
        let model = selected_model(&page.data, None).ok_or("Missing model")?;
        assert_eq!(model.model, "latest-model");
        assert_eq!(model.display_name, "Latest Model");
        let mut ordered = fixture.clone();
        let mut second = fixture["data"][0].clone();
        second["model"] = json!("saved-model");
        second["isDefault"] = json!(true);
        ordered["data"] = json!([fixture["data"][0], second]);
        let ordered = model_page(&ordered)?;
        assert_eq!(
            selected_model(&ordered.data, None).map(|m| m.model.as_str()),
            Some("latest-model")
        );
        assert_eq!(
            selected_model(&ordered.data, Some("saved-model")).map(|m| m.model.as_str()),
            Some("saved-model")
        );
        assert_eq!(selected_effort(Some(model), None), Some("medium"));
        assert_eq!(selected_effort(Some(model), Some("high")), Some("high"));
        assert_eq!(selected_effort(Some(model), Some("xhigh")), Some("medium"));
        assert_eq!(
            selected_model(&page.data, Some("removed-model")).map(|m| m.model.as_str()),
            Some("latest-model")
        );
        let params = turn_params("thread", vec![], Some(&model.model), Some("high"));
        assert_eq!(params["model"], "latest-model");
        assert_eq!(params["effort"], "high");
        assert_eq!(params["summary"], "detailed");
        let changed = turn_params("thread", vec![], Some("another-model"), Some("low"));
        assert_eq!(changed["model"], "another-model");
        assert_eq!(changed["effort"], "low");
        assert_eq!(changed["threadId"], params["threadId"]);
        let mut hidden = fixture.clone();
        hidden["data"][0]["hidden"] = json!(true);
        assert!(model_page(&hidden)?.data.is_empty());
        let empty = model_page(&json!({"data":[],"nextCursor":null}))?;
        assert!(selected_model(&empty.data, Some("saved-model")).is_none());
        assert_eq!(selected_effort(None, None), None);
        let mut without_default = fixture.clone();
        without_default["data"][0]["defaultReasoningEffort"] = Value::Null;
        let without_default = model_page(&without_default)?;
        assert_eq!(selected_effort(without_default.data.first(), None), None);
        let omitted = turn_params("thread", vec![], None, None);
        assert!(omitted.get("model").is_none());
        assert!(omitted.get("effort").is_none());
        assert_eq!(omitted["summary"], "detailed");
        assert!(model_page(&json!({"data":[{"id":"incomplete"}]})).is_err());
        assert!(model_page(&json!({})).is_err());
        Ok(())
    }
    #[test]
    fn device_code_protocol_does_not_read_credentials() {
        let init = initialize(1);
        assert_eq!(init["params"]["capabilities"]["experimentalApi"], true);
        assert_eq!(dynamic_tools().as_array().unwrap().len(), 15);
    }
    #[test]
    #[ignore = "requires an installed Codex CLI; reads account status without starting a model turn"]
    fn installed_codex_auth_handshake() {
        let c = Client::start(true, false).unwrap();
        c.send(initialize(1)).unwrap();
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(30);
        let mut account = false;
        while std::time::Instant::now() < deadline {
            for msg in c.drain() {
                let v = msg.unwrap();
                if v["id"] == 1 {
                    assert!(v.get("error").is_none(), "initialization failed");
                    c.send(json!({"method":"initialized","params":{}})).unwrap();
                    c.send(json!({"id":2,"method":"account/read","params":{"refreshToken":false}}))
                        .unwrap();
                }
                if v["id"] == 2 {
                    assert!(v.get("error").is_none(), "account read failed");
                    account = true;
                }
            }
            if account {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(40));
        }
        assert!(account, "account status timed out");
    }
}
